server:
  port: 8080

spring:
  application:
    name: blog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ll.blog.model.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ll.blog: debug
    org.springframework.boot.autoconfigure.jdbc: debug
    org.springframework.boot.context.properties: debug

auth:
  token:
    expire: 7200

aliyun:
  oss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucketName: ll-cc-blog
    region: cn-chengdu

hexo:
  posts-path: classpath:hexo/source/_posts/